url: http://stefaniuk.co.uk
permalink: /:title

title: Dan's Blog
description: >
  A blog about software engineering

author: Daniel Stefaniuk
email: daniel.stefaniuk@gmail.com
github_username: stefaniuk
linkedin_username: dstefaniuk
stackoverflow_username: 472150
twitter_username: danstefaniuk

timezone: Europe/London
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  permalinks:
    tag: '/tags/:name/'

sass:
  style: compressed

exclude:
  - LICENCE.md
  - Makefile
  - README.md
  - TODO.md
